### ISSUE TITLE
Signals not disconnected

### ISSUE THREAD

**Issue by tashrifbillah** [pnlbwh/SlicerDiffusionQC#12]
`gradqclib/slicerUserInteraction.py`: The following error message shows up when MRML scene is closed or Slicer is closed. This is a negligible issue. An way around could be to disconnect all signals when `Save` is selected or to introduce an `Exit` button before closing, within which all signals are disconnected. See `gradqclib/slicerUserInteraction.py: 137`.

``Traceback (most recent call last):
  File "/home/tb571/.config/NA-MIC/Extensions-27483/DiffusionQC/lib/Slicer-4.9/qt-scripted-modules/gradqclib/slicerUserInteraction.py", line 232, in gradientUpdate
    index = self.tableHandle.selectedIndexes()[0]
IndexError: tuple index out of range
Traceback (most recent call last):
  File "/home/tb571/.config/NA-MIC/Extensions-27483/DiffusionQC/lib/Slicer-4.9/qt-scripted-modules/gradqclib/slicerUserInteraction.py", line 232, in gradientUpdate
    index = self.tableHandle.selectedIndexes()[0]
IndexError: tuple index out of range
Traceback (most recent call last):
  File "/home/tb571/.config/NA-MIC/Extensions-27483/DiffusionQC/lib/Slicer-4.9/qt-scripted-modules/gradqclib/slicerUserInteraction.py", line 232, in gradientUpdate
    index = self.tableHandle.selectedIndexes()[0]
IndexError: tuple index out of range
Traceback (most recent call last):
  File "/home/tb571/.config/NA-MIC/Extensions-27483/DiffusionQC/lib/Slicer-4.9/qt-scripted-modules/gradqclib/slicerUserInteraction.py", line 232, in gradientUpdate
    index = self.tableHandle.selectedIndexes()[0]
IndexError: tuple index out of range
Traceback (most recent call last):
  File "/home/tb571/.config/NA-MIC/Extensions-27483/DiffusionQC/lib/Slicer-4.9/qt-scripted-modules/gradqclib/slicerUserInteraction.py", line 232, in gradientUpdate
    index = self.tableHandle.selectedIndexes()[0]
IndexError: tuple index out of range
Traceback (most recent call last):
  File "/home/tb571/.config/NA-MIC/Extensions-27483/DiffusionQC/lib/Slicer-4.9/qt-scripted-modules/gradqclib/slicerUserInteraction.py", line 232, in gradientUpdate
    index = self.tableHandle.selectedIndexes()[0]
IndexError: tuple index out of range`

```

**Comment by tashrifbillah** [comment]
Fixed by

https://github.com/pnlbwh/SlicerDiffusionQC/pull/27/commits/92576be1d4aee5699185c3a93edc24fe9e072fe4
