### ISSUE TITLE
[Win/MAC] import numpy error

### ISSUE THREAD

**Issue by tashrifbillah** [pnlbwh/SlicerDiffusionQC#38]
# Error
The following error is observed on Win and MAC (on the `PythonInteractor`):

```bash
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "C:/Users/tashr/Downloads/Slicer-dqc/bin/../lib/Slicer-4.10/qt-scripted-modules/DICOMScalarVolumePlugin.py", line 1, in <module>
    import numpy
  File "C:\Users\tashr\AppData\Roaming\NA-MIC\Extensions-28257\DiffusionQC\Lib\site-packages\numpy\__init__.py", line 142, in <module>
    from . import core
  File "C:\Users\tashr\AppData\Roaming\NA-MIC\Extensions-28257\DiffusionQC\Lib\site-packages\numpy\core\__init__.py", line 71, in <module>
    raise ImportError(msg)
ImportError: 

IMPORTANT: PLEASE READ THIS FOR ADVICE ON HOW TO SOLVE THIS ISSUE!

Importing the multiarray numpy extension module failed.  Most
likely you are trying to import a failed build of numpy.
Here is how to proceed:
- If you're working with a numpy git repository, try `git clean -xdf`
  (removes all files not under version control) and rebuild numpy.
- If you are simply trying to use the numpy version that you have installed:
  your installation is broken - please reinstall numpy.
- If you have already reinstalled and that did not fix the problem, then:
  1. Check that you are using the Python you expect (you're using C:\Users\tashr\Downloads\Slicer-dqc\bin\SlicerApp-real.exe),
     and that you have no directories in your PATH or PYTHONPATH that can
     interfere with the Python and numpy versions you're trying to use.
  2. If (1) looks fine, you can open a new issue at
     https://github.com/numpy/numpy/issues.  Please include details on:
     - how you installed Python
     - how you installed numpy
     - your operating system
     - whether or not you have multiple versions of Python installed
     - if you built from source, your compiler versions and ideally a build log

     Note: this error has many possible causes, so please don't comment on
     an existing issue about this - open a new one instead.

Original error was: DLL load failed: The specified module could not be found.
```

# Solution
From the above, find the path where numpy is installed: 
```C:\Users\tashr\AppData\Roaming\NA-MIC\Extensions-28257\DiffusionQC\Lib\site-packages\numpy\```
and delete it.

**Comment by tashrifbillah** [comment]
The error does not happen in Linux. Also, it does not happen with Slicer-4.11 which runs Python 3.

**Comment by tashrifbillah** [comment]
cc @yrathi
