### ISSUE TITLE
Fail to instantiate module  "GradQC" with Slicer 4.11

### ISSUE THREAD

**Issue by amvoidhub** [pnlbwh/SlicerDiffusionQC#46]
After I install DiffusionQC extension, there comes an error whenever I start Slicer:

Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/amvoid/ProgramFiles/Slicer/lib/Python/lib/python3.6/imp.py", line 170, in load_source
    module = _exec(spec, sys.modules[name])
  File "<frozen importlib._bootstrap>", line 618, in _exec
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/amvoid/ProgramFiles/Slicer/NA-MIC/Extensions-29738/DiffusionQC/lib/Slicer-4.11/qt-scripted-modules/GradQC.py", line 5, in <module>
    from gradqclib.slicerUserInteraction import slicerGUI
  File "/home/amvoid/ProgramFiles/Slicer/NA-MIC/Extensions-29738/DiffusionQC/lib/Slicer-4.11/qt-scripted-modules/gradqclib/slicerUserInteraction.py", line 6, in <module>
    from diffusionqclib.dwi_attributes import dwi_attributes
  File "/home/amvoid/ProgramFiles/Slicer/NA-MIC/Extensions-29738/DiffusionQC/lib/python3.6/site-packages/diffusionqclib/dwi_attributes.py", line 4, in <module>
    from nhdr_write import nhdr_write
ModuleNotFoundError: No module named 'nhdr_write'
loadSourceAsModule - Failed to load file "/home/amvoid/ProgramFiles/Slicer/NA-MIC/Extensions-29738/DiffusionQC/lib/Slicer-4.11/qt-scripted-modules/GradQC.py"  as module "GradQC" !
Fail to instantiate module  "GradQC"
The following modules failed to be instantiated:
   GradQC

**Comment by tashrifbillah** [comment]
Hi, sorry about the error. I believe it is due to issue #42. Recently Slicer 4.11 has changed in a way that requires us to import functions in a different way which I haven't gotten the time to do yet.

In the meantime, can you get a Slicer-4.10, affect [this](#38) fix, and thereby use GradQC?

**Comment by amvoidhub** [comment]
> Hi, sorry about the error. I believe it is due to issue #42. Recently Slicer 4.11 has changed in a way that requires us to import functions in a different way which I haven't gotten the time to do yet.
> 
> In the meantime, can you get a Slicer-4.10, affect [this](#38) fix, and thereby use GradQC?

**Comment by amvoidhub** [comment]
I reinstalled Slicer-4.10 version, but didn't find DiffusionQC Extension at all...

![image](https://user-images.githubusercontent.com/20393841/116178716-b0c33880-a748-11eb-8709-67e8ef08c94a.png)

That is weird.

**Comment by tashrifbillah** [comment]
Type `DiffusionQC` in the search bar, it should show up and let you click `INSTALL`.

**Comment by amvoidhub** [comment]
> Type `DiffusionQC` in the search bar, it should show up and let you click `INSTALL`.

Thank u. 
I made it work in Ubuntu. (But still didn't work in windows. )
I tested it with s sample dwi image in method i), and failed with another error: 

```
Traceback (most recent call last):
  File "/home/amvoid/.config/NA-MIC/Extensions-27501/DiffusionQC/lib/Slicer-4.10/qt-scripted-modules/GradQC.py", line 358, in onApplyButton
    cliNode= slicer.cli.run(diffusionQCcli, parameters)
  File "/home/amvoid/ProgramFiles/Slicer/bin/Python/slicer/cli.py", line 82, in run
    logic.Apply(node, update_display)
TypeError: Apply argument 1: method requires a VTK object
```

**Comment by tashrifbillah** [comment]
Are you saying you did https://github.com/pnlbwh/SlicerDiffusionQC#tests (i) ?

In any case, can you try (ii) ?

Email tbillah@bwh.harvard.edu to obtain my office hour info so we can take a look at it together.
